---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes
    clean: yes
  become: yes