---
# - hosts: all
# - hosts: macos
#   become: no
#   tasks:
#     - name: Test
#       ansible.builtin.debug:
#         msg: "{{ ansible_facts.hostname }} {{ ansible_facts.default_ipv4.address }} {{ ansible_facts.model }}"
# - hosts:
#     pihole2:
#       ansible_user: root
- name: Setup PiHole
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
        clean: yes
    - name: Install curl htop
      ansible.builtin.apt:
        pkg:
        - curl
        - htop
    # - name: Update PiHole pull
    #   ansible.builtin.shell:
    #     cmd: "curl -sSL https://install.pi-hole.net | bash"

    # - name: Test
    #   ansible.builtin.debug:
    #     # var: ansible_facts
    #     msg: "{{ ansible_facts.hostname }} {{ ansible_facts.eth0.ipv4.address }}"
    # - name: Update RasPi OS
    #   ansible.builtin.include_tasks:
    #     file: tasks/apt.yml
    # - name: Reboot the machine
    #   ansible.builtin.reboot:
    #   become: yes
    # - name: Update PiHole
    #   ansible.builtin.include_tasks:
    #     file: tasks/pihole.yml


