---
version: '3'
services:
  octoprint:
    build: .
    image: walchko/octoprint:0.7
    container_name: octoprint
    ports:
      - 5000:5000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./config:/home/octoprint/.octoprint
