---
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole-docker:
    container_name: pihole-docker
    image: pihole/pihole:latest
    #cgroupVersion: v1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp"  # only if using pihole for dhcp
      - "80:80/tcp"
      - "443:443/tcp"
    hostname: pihole-dalek
    environment:
      TZ: ${TIMEZONE}
      # DNSMASQ_USER: root
      # PIHOLE_UID: 1000
      # PIHOLE_GID: 0
      VIRTUAL_HOST: pihole-docker.local
      # ServerIP: ${HOST_IP}
      WEBPASSWORD: ${PASSWORD}
      WEBTHEME: "default-dark"
      TEMPERATUREUNIT: "f"
      #DOCKER_OPTS: native.cgroupdriver=cgroupfs
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - ${DNS_1}
      - ${DNS_2}
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # only needed if using pihole for DHCP
    restart: unless-stopped
