---
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole-docker:
    container_name: pihole-docker
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp"  # dhcp
      - "80:80/tcp"
      - "443:443/tcp"
    hostname: pihole-docker
    environment:
      TZ: 'America/Chicago'
      VIRTUAL_HOST: pihole-docker.local
      ServerIP: ${HOST_IP}
      WEBPASSWORD: ${PASSWORD}
      WEBTHEME: "default-dark"
      TEMPERATUREUNIT: "f"
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - ${DNS_1}
      - ${DNS_2}
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
