---
version: '3'

services:
  jupyter-server:
    build: .
    image: walchko/jupyter-server:0.1
    container_name: jupyter-server
    ports:
      - "8888:8888/tcp"
    hostname: jupyter-server
    volumes:
      - '/home/kevin/github:/home/kevin/github'
      - '/home/kevin/tmp:/home/kevin/tmp'
    restart: unless-stopped
