---
version: '3'

services:
  jupyter:
    build: .
    image: walchko/jupyter:0.1
    container_name: jupyter
    ports:
      - "28888:8888/tcp"
    hostname: jupyter
    volumes:
      # - '/home/kevin/github/bearsnacks:/home/jupuser/github'
      # - '/home/kevin/tmp:/home/jupuser/tmp'
      #- './home:/home/jupuser'
      - ./files:/files
    restart: unless-stopped
    #entrypoint: /bin/bash
    stdin_open: true
    environment:
      TZ: 'America/Chicago'
