---
- name: Setup File Server
  hosts: all
  become: yes
  tasks:
    - name: Get curl
      ansible.builtin.apt:
        pkg:
        - curl
    - name: Add Plex apt repo and GPG key
      ansible.builtin.shell: |
        curl -sS https://downloads.plex.tv/plex-keys/PlexSign.key | gpg --dearmor | tee /usr/share/keyrings/plex.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/plex.gpg] https://downloads.plex.tv/repo/deb public main" > /etc/apt/sources.list.d/plexmediaserver.list
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
        clean: yes
    - name: Install Plex
      ansible.builtin.apt:
        pkg:
        - gnupg
        - curl
        - nfs-common
        # - cifs-utils
        - plexmediaserver