---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    hostname: plex-desktop
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - ./library:/config
      - /mnt/usbdrive:/media
    restart: unless-stopped
