---
version: "3"
services:
  plex:
    # this works: 1.32.0.6918-6f393eda1-ls162 Apr 17 2023
    # image: ghcr.io/linuxserver/plex:1.32.0.6918-6f393eda1-ls162
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    # network_mode: host # this works for linux
    hostname: dalek
    environment:
      - PUID=501 #1000
      - PGID=501 #1000
      - VERSION=docker
      # - PLEX_CLAIM=claim-6G6q3f4WL9hhJyFfyszw #optional
    volumes:
      - ./library:/config
      #- ../../../Movies:/media
      #- /mnt/usbdrive:/media
      - /Volumes/arrow:/media
      # - /tmp:/media
    restart: unless-stopped
    ports: # need to do this on macOS, linux doesn't need it
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
