---
version: '3'

services:
  pihole-recursive:
    build: .
    image: walchko/pihole-recursive:0.1
    container_name: pihole-recursive
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "5335:5335/tcp"
      - "5335:5335/udp"
    hostname: pihole-docker
    environment:
      TZ: 'America/Chicago'
      # VIRTUAL_HOST: pihole-docker.local
      ServerIP: ${HOST_IP}
      WEBPASSWORD: ${PASSWORD}
      # DNS1: 127.0.0.1#5335
      # DNS2: 127.0.0.1#5335
      PIHOLE_DNS_: 127.0.0.1#5335;127.0.0.1#5335
      DNSSEC: "true"
      TEMPERATUREUNIT: "f"
      WEBTHEME: "default-dark"
    # Volumes store your data between container upgrades
    # volumes:
    #   - './etc-pihole/:/etc/pihole/'
    #   - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # dns:
    #   - ${DNS_1}
      # - ${DNS_2}
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN
    restart: unless-stopped
