
FROM alpine:3.19

RUN apk --update --no-cache add \
    ca-certificates \
    git \
    openssh-client \
    openssl \
    py3-cryptography \
    py3-pip \
    py3-yaml \
    python3 \
    rsync \
    sshpass \
    ansible

# RUN pip install -U \
#     setuptools \
#     pip \
#     ansible